Tag.create!([
  {name: "aquarium", stay_time: 120},
  {name: "art_gallery", stay_time: 120},
  {name: "bakery", stay_time: 30},
  {name: "bar", stay_time: 150},
  {name: "book_store", stay_time: 30},
  {name: "cafe", stay_time: 60},
  {name: "clothing_store", stay_time: 60},
  {name: "department_store", stay_time: 60},
  {name: "electronics_store", stay_time: 60},
  {name: "food", stay_time: 150},
  {name: "furniture_store", stay_time: 60},
  {name: "grocery_or_supermarket", stay_time: 30},
  {name: "library", stay_time: 90},
  {name: "meal_takeaway", stay_time: 30},
  {name: "movie_theater", stay_time: 150},
  {name: "museum", stay_time: nil},
  {name: "park", stay_time: 30},
  {name: "pet_store", stay_time: 30},
  {name: "pharmacy", stay_time: 30},
  {name: "restaurant", stay_time: 150},
  {name: "shoe_store", stay_time: 30},
  {name: "shopping_mall", stay_time: 60},
  {name: "spa", stay_time: 180},
  {name: "tourist_attraction", stay_time: 60},
  {name: "place_of_worship", stay_time: 60}
])
